# Generated by Django 2.0.7 on 2019-05-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
